name: appecomerce
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.8.1

#---packages---
dependencies:
  flutter:
    sdk: flutter

# Utility Packages
  http: ^1.1.0
  intl: ^0.18.0
  logger: ^2.0.1
  flutter_native_splash: ^2.3.2
  url_launcher: ^6.1.12
  smooth_page_indicator: ^1.1.0

#Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.8
#state management
  get: ^4.6.5
  get_storage: ^2.1.1

#-----packages end---
dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

#--local assets---
  assets:
    - assets/logos/
    - assets/images/brands/
    - assets/icons/
    - assets/images/on_boarding_images/
#---local fonts---
fonts:
  - family: Poppins
    fonts:
      - asset: assets/fonts/Poppins-Light.ttf
        weight: 300
      - asset: assets/fonts/Poppins-Regular.ttf
        weight: 400
      - asset: assets/fonts/Poppins-Italic.ttf
        style: italic
      - asset: assets/fonts/Poppins-Medium.ttf
        weight: 500
      - asset: assets/fonts/Poppins-MediumItalic.ttf
        weight: 500
        style: italic
      - asset: assets/fonts/Poppins-SemiBold.ttf
        weight: 600
      - asset: assets/fonts/Poppins-Bold.ttf
        weight: 800
